# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: yarn install
    displayName: Install Yarn

  - script: yarn gulp "clean"
    displayName: "Clean Workspace"

  - script: yarn test
    displayName: "Running Unit Tests"

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TEST-*.xml'

  - script: yarn gulp "app:zip-linux"
    displayName: "Package Zip Linux Artifact"

  - task: CopyFiles@2
    inputs:
      Contents: 'build/*.zip'
      TargetFolder: '$(build.artifactstagingdirectory)/app'
      OverWrite: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/app'
      artifactName: "Zip - Linux Application"

  - script: yarn gulp "app:appimage-linux"
    displayName: "Package AppImage Artifact"

  - task: CopyFiles@2
    inputs:
      Contents: 'build/*.AppImage'
      TargetFolder: '$(build.artifactstagingdirectory)/appimage'
      OverWrite: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/appimage'
      artifactName: "AppImage - Linux Application"





