# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '>=16.x'

  - script: npm install
    displayName: "Install Dependencies"

  - script: npm run gulp clean
    displayName: "Clean Workspace"

  - script: npm run lint
    displayName: "Running ESLint"

  - script: npm run test
    displayName: "Running Unit Tests"

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TEST-*.xml'

  - script: npm run gulp "app:zip-linux"
    displayName: "Package and Zip Linux Artifacts"

  - task: CopyFiles@2
    inputs:
      Contents: 'build/*.zip'
      TargetFolder: '$(build.artifactstagingdirectory)/app'
      OverWrite: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/app'
      artifactName: "Zip - Linux Application"


  # https://github.com/AppImage/AppImageKit/wiki/FUSE
  - script: sudo apt-get install libfuse2

  - script: npm run gulp "app:appimage-linux"
    displayName: "Package AppImage Artifact"

  - task: CopyFiles@2
    inputs:
      Contents: 'build/*.AppImage'
      TargetFolder: '$(build.artifactstagingdirectory)/appimage'
      OverWrite: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/appimage'
      artifactName: "AppImage - Linux Application"





