# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: yarn install
    displayName: "Install Yarn"

  - script: yarn gulp "clean"
    displayName: "Clean Workspace"

  - script: yarn test
    displayName: "Running Unit Tests"

  - script: yarn gulp "app:package-macos"
    displayName: "Package macOS Artifacts"

#
#  FIXME: Zipping the macos binary fails due to invalid symlinks.
#
#  - script: yarn gulp "app:zip-macos"
#    displayName: "Package and Zip macOS Artifacts"
#
#  - task: CopyFiles@2
#    inputs:
#      Contents: 'build/*.zip'
#      TargetFolder: '$(build.artifactstagingdirectory)/app'
#      OverWrite: true
#
#  - task: PublishBuildArtifacts@1
#    inputs:
#      pathtoPublish: '$(Build.ArtifactStagingDirectory)/app'
#      artifactName: "Zip - macOS Application"