# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

jobs:
- job: WebExtension
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  
  - task: NodeTool@0
    inputs:
      versionSpec: '>=16.x'

  - script: yarn install
    displayName: "Install Yarn"

  - script: yarn gulp "clean"
    displayName: "Clean Workspace"

  - script: yarn lint
    displayName: "Running ESLint"

  - script: yarn test
    displayName: "Running Unit Tests"

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TEST-*.xml'

  - script: yarn gulp "wx:package-xpi"
    displayName: "Package and Zip WebExtension Artifact"

  - task: CopyFiles@2
    inputs:
      Contents: 'build/*'
      TargetFolder: '$(build.artifactstagingdirectory)'
      OverWrite: true
      CleanTargetFolder: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/build'
      artifactName: "XPI - Thunderbird WebExtension"

