FROM alpine:latest

RUN apk add dovecot
#RUN apk add bash mc

RUN adduser vmail -D

COPY local.conf /etc/dovecot/local.conf
COPY dovecot-openssl.conf /etc/dovecot/dovecot-openssl.conf

RUN echo "user:{plain}pencil::::::" > /etc/dovecot/users && \
    echo "user2:{plain}€äöü§²³::::::" >> /etc/dovecot/users

RUN openssl req -new -x509 -nodes -days 365 \
    -config "/etc/dovecot/dovecot-openssl.conf" \
    -out "/etc/ssl/certs/dovecot.pem" \
    -keyout "/etc/ssl/private/dovecot.pem" && \
    chmod 0600 "/etc/ssl/private/dovecot.pem"

EXPOSE 143 993 4190

CMD /usr/sbin/dovecot && tail -f /var/log/dovecot.log
